export Home from './Home/Home'
export FormRequestWrapper from './commons/FormRequestWrapper'
export FormRadiobuttomGeneric from './commons/FormRadiobuttomGeneric'
export IsClientForm from './SolicitudServicio/IsClientForm'
export SolicitudRFC from './SolicitudServicio/SolicitudRFC'
export SolicitudGeneralesEmpresa from './SolicitudServicio/SolicitudGeneralesEmpresa'
export SolicitudServicioRequerido from './SolicitudServicio/SolicitudServicioRequerido'
export SolicitudServicioAgricola from './SolicitudServicio/agricola'
